#!/bin/bash

make distclean

echo autoclean: cleaning root
rm -rf aclocal.m4 \
       autom4te.cache \
       autoscan.log \
       build-aux \
       compile \
       config.guess \
       config.h \
       config.h.in \
       config.h.in~ \
       config.log \
       config.status \
       config.sub \
       configure \
       depcomp \
       install-sh \
       libtool \
       ltmain.sh \
       missing \
       Makefile.in \
       Makefile \
       stamp-h1

